import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Student } from './api/db'

const InProcess: NextPage<{data : Student[]}> = ({data} : {data : Student[]}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        data.map((student : Student)=>{
          return(
            <div key={student.id}>
              <p>{student.nombre}</p>
              <p>Calificaciones:</p>
              <p>Primer Cuatrimestre: {student.calificaciones.PrimerCuatr}</p>
              <p>Segundo Cuatrimestre: {student.calificaciones.SegundoCuatr}</p>
              <hr></hr>
            </div>
          )
        }) 
      }
    </div>
  )
}

export default InProcess
export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/inprocess")
  const data : Student[] = await res.json();  
  return {
    props: { data }
  }
}